const loanCalculatorTypes = {
  LOAN_CALCULATOR_SETTINGS_FETCH: 'LOAN_CALCULATOR_SETTINGS_FETCH',
  LOAN_CALCULATOR_SETTINGS_SUCCESS: 'LOAN_CALCULATOR_SETTINGS_SUCCESS',
  LOAN_CALCULATOR_SETTINGS_ERROR: 'LOAN_CALCULATOR_SETTINGS_ERROR',
  LOAN_CALCULATOR_DATA_FETCH: 'LOAN_CALCULATOR_DATA_FETCH',
  LOAN_CALCULATOR_DATA_SUCCESS: 'LOAN_CALCULATOR_DATA_SUCCESS',
  LOAN_CALCULATOR_DATA_ERROR: 'LOAN_CALCULATOR_DATA_FETCH',
};

export default loanCalculatorTypes;
